UNIVERSE = ["SPY", "QQQ", "IWM", "DIA", "EEM"]

RSI_PERIOD = 2
RSI_OVERSOLD = 10
TREND_MA = 200
EXIT_MA = 5
ATR_PERIOD = 14
ATR_STOP_MULT = 2.0

RISK_PER_TRADE = 0.01
MAX_OPEN_POSITIONS = 3
KILL_SWITCH_DRAWDOWN = 0.20
